services:
  - type: web
    name: ctetproject-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python backend/manage.py collectstatic --noinput
    startCommand: |
      python backend/manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ctetproject.settings
      - key: SECRET_KEY
        value: your_secret_key
      - key: ALLOWED_HOSTS
        value: 'conferencetravel.onrender.com'

  - type: web
    name: ctetproject-frontend
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      npm start
    envVars:
      - key: PORT
        value: '3000'