services:
  - type: web
    name: myproject
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      cd ../frontend
      npm install
      npm run build
    startCommand: |
      cd backend
      gunicorn myproject.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings