services:
  - type: web
    name: ctetproject-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ctetproject.settings
      - key: SECRET_KEY
        value: your_secret_key
      - key: ALLOWED_HOSTS
        value: 'conferencetravel.onrender.com'