services:
  - type: web
    name: ctetproject-backend
    env: python
    buildCommand: |
      cd ctetproject/backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      cd ../../frontend
      npm install
      npm run build
      cd ../backend
    startCommand: |
      cd ctetproject/backend/ctetproject
      gunicorn ctetproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ctetproject.settings
      - key: SECRET_KEY
        value: your_secret_key
      - key: ALLOWED_HOSTS
        value: 'conferencetravel.onrender.com'